# Generated by Django 5.2.3 on 2025-07-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_producto_estado_alter_producto_numero_serie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cotizacion_detalle',
            options={},
        ),
        migrations.RenameField(
            model_name='cotizacion',
            old_name='cotizacion_codigo',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='precio_cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='total_cotizacion_valor',
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='cantidad_producto',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='precio_cotizado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='creacion_usuario',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='modificacion_usuario',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='creacion_usuario',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='miapp.iva'),
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='modificacion_usuario',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='cotizacion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cotizacion_detalle',
            table=None,
        ),
    ]
