# Generated by Django 5.2.3 on 2025-07-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_remove_factura_descuento_factura_anulada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_detalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura_detalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Anulado')], default=1),
        ),
    ]
