# Generated by Django 5.2.3 on 2025-07-04 06:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_remove_factura_descuento_factura_anulada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='iva', max_length=50, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'verbose_name': 'iva',
                'verbose_name_plural': 'ivas',
                'db_table': 'iva',
            },
        ),
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='cotizacion_detalle',
            options={'verbose_name': 'Detalle de Cotización', 'verbose_name_plural': 'Detalles de Cotización'},
        ),
        migrations.RenameField(
            model_name='cotizacion_detalle',
            old_name='Cotizacion',
            new_name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cantidad_productos',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='total',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='anulada',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cantidad_productos',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='descuento_total',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='motivo_anulacion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='precio_cotizacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='total_cotizacion_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='factura_detalle',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='factura_detalle',
            name='precio_factura',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='factura_detalle',
            name='total_factura_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Anulado')], default=1),
        ),
        migrations.AlterField(
            model_name='factura_detalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Anulado')], default=1),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='iva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='miapp.iva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura_detalle',
            name='iva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='miapp.iva'),
            preserve_default=False,
        ),
    ]
