# Generated by Django 5.2.3 on 2025-07-04 07:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_iva_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_detalle',
            name='total_factura_valor',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='iva',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
