# Generated by Django 5.2.3 on 2025-07-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_empleado_user_alter_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('creación', 'Creación'), ('actualización', 'Actualización')], max_length=20)),
                ('stock_anterior', models.PositiveIntegerField()),
                ('cantidad_cambiada', models.IntegerField()),
                ('stock_nuevo', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.producto')),
            ],
            options={
                'verbose_name': 'historial producto',
                'verbose_name_plural': 'historial productos',
                'db_table': 'historial_producto',
            },
        ),
    ]
