# Generated by Django 5.2.3 on 2025-07-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_factura_detalle_precio_unitario_producto_stock_and_more'),
        ('miapp', '0004_alter_factura_detalle_total_factura_valor_and_more'),
    ]

    operations = [
    ]
