# Generated by Django 5.2.3 on 2025-07-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_alter_producto_numero_serie_historialproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='unidad',
        ),
    ]
