# Generated by Django 5.2.3 on 2025-07-11 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_remove_producto_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='cantidad_producto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp.iva'),
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miapp.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    ]
