# Generated by Django 5.2.3 on 2025-07-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_alter_cotizacion_detalle_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(default='@', max_length=40, unique=True),
        ),
    ]
