# Generated by Django 5.2.3 on 2025-07-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_alter_empleado_cedula_alter_empleado_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='factura_codigo',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='Codigo_Cargo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='@', max_length=40, unique=True),
        ),
    ]
