# Generated by Django 5.2.3 on 2025-07-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_producto_imagen_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen_producto',
            new_name='imagen',
        ),
    ]
