# Generated by Django 5.2.4 on 2025-07-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('miapp', '0016_remove_proveedor_producto_compra_detallecompra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleCompra',
            new_name='Detalle_Compra',
        ),
    ]
